import { dimension, initialVersion } from './types.ts';
import type { Dataset, Electrode, Material } from './types.ts';
import { validateDataset } from './validation.ts';
export function importPayload(input: unknown):Dataset{
  const old=input as Record<string,unknown>;if(old?.schemaVersion===7)return validateDataset(input);
  if(old?.schemaVersion!==1||!Array.isArray(old.materials))throw Error('Import a schemaVersion 7 backup or a legacy materials JSON export. Legacy design exports must be recreated as versioned plans.');
  const result:Dataset={schemaVersion:7,materials:[],electrodes:[],parts:[],boms:[],plans:[]};
  for(const item of old.materials){const r=item as Record<string,unknown>;if(typeof r.name!=='string'||!['Cathode','Anode'].includes(String(r.type)))throw Error('Invalid legacy electrode record.');const num=(k:string)=>{if(r[k]==null||r[k]==='')return null;if(typeof r[k]!=='number'||!Number.isFinite(r[k])||r[k]<0)throw Error(`Invalid legacy ${k}.`);return r[k] as number;};const material:Material={...initialVersion(r.name+' material'),source:String(r.source??'Legacy import'),notes:'Cs migrated from legacy electrode record; verify material/test basis.',electrodeType:r.type as Material['electrodeType'],chemistry:String(r.chemistry??''),supplier:String(r.supplier??''),cs:num('cs')};const load=num('loading'),tol=num('tolerance'),thickness=num('thickness'),thicknessTol=num('thicknessTolerance');const electrode:Electrode={...initialVersion(r.name),source:String(r.source??'Legacy import'),notes:'Loading is interpreted as both-side total. Legacy calculated capacities are ignored. Missing thickness tolerance remains unknown.',materialId:material.id,utility:num('utility'),loading:load!=null&&tol!=null?dimension(load,load*tol/100):null,density:num('density'),thickness:thickness!=null&&thicknessTol!=null?dimension(thickness,thickness*thicknessTol/100):null,collectorMaterial:['Al','Cu','Other'].includes(String(r.collectorMaterial))?r.collectorMaterial as Electrode['collectorMaterial']:'Unknown',collectorThicknessUm:num('collectorThickness'),collectorGrade:String(r.collectorGrade??'')};result.materials.push(material);result.electrodes.push(electrode);}
  return validateDataset(result);
}
