import { dimension as d } from './types.ts';
import type { Dataset, Version } from './types.ts';
const v = (id: string, name: string): Version => ({ id, lineageId: id, revision: 1, name, createdAt: '2026-09-30T00:00:00.000Z', source: 'Reference screenshot / illustrative specifications', notes: 'Demonstration record; not a supplier specification.' });
export function seedDataset(): Dataset { return { schemaVersion: 7,
  materials: [{ ...v('material-c1','Cathode reference'), electrodeType:'Cathode', chemistry:'Not specified', supplier:'', cs:154 }, { ...v('material-a1','Anode demonstration'), electrodeType:'Anode', chemistry:'Illustrative graphite', supplier:'', cs:350 }],
  electrodes: [{ ...v('electrode-c1','Cathode reference electrode'), materialId:'material-c1', utility:95.1, loading:d(206,4.12), density:null, thickness:d(.201,.00402), collectorMaterial:'Al', collectorThicknessUm:15, collectorGrade:'Illustrative foil' }, { ...v('electrode-a1','Anode demonstration electrode'), materialId:'material-a1', utility:100, loading:d(95,1.9), density:null, thickness:d(.145,.00402), collectorMaterial:'Cu', collectorThicknessUm:10, collectorGrade:'Illustrative foil' }],
  parts: [{ ...v('housing-r1','Reference housing'), role:'Housing', partNumber:'DEMO-HOUSING', material:'Al', supplier:'', drawing:'', thickness:d(.3), internalSpace:d(28.5,0,.2), width:null,height:null }, { ...v('separator-r1','Reference separator'), role:'Separator',partNumber:'DEMO-SEP',material:'Not specified',supplier:'',drawing:'',thickness:d(.012),internalSpace:null,width:null,height:null },{ ...v('iso-r1','ISO insulation'),role:'Insulation',partNumber:'DEMO-ISO',material:'Not specified',supplier:'',drawing:'',thickness:d(.2),internalSpace:null,width:null,height:null }],
  boms: [{ ...v('bom-r1','Reference mechanical BOM'),housingId:'housing-r1',items:[{partId:'separator-r1',quantity:1,usage:'perSeparatorLayer'},{partId:'iso-r1',quantity:2,usage:'perCell'}] }],
  plans: [{ ...v('plan-r1','Reference LC stack'),cathodeId:'electrode-c1',anodeId:'electrode-a1',bomId:'bom-r1',mode:'specified',sheets:36,stacks:2,extraSeparatorLayers:6,stackClearance:d(.3),assemblyClearance:d(1),overlapAreaCm2:null,minimumNp:1,maximumNp:null }]
}; }
