import { collections, bounds } from './types.ts';
import type { Dataset, Dimension, Version } from './types.ts';
const text = (v: unknown, name: string) => { if (typeof v !== 'string') throw Error(`${name} must be text.`); };
const number = (v: unknown, name: string, nullable = false) => { if (nullable && v === null) return; if (typeof v !== 'number' || !Number.isFinite(v) || v < 0) throw Error(`${name} must be a finite nonnegative number.`); };
export function validateDimension(d: Dimension | null, label: string, optional = false) { if (d === null && optional) return; if (!d || typeof d !== 'object') throw Error(`${label} needs nominal, lower and upper deviations.`); for (const k of ['nominal','minus','plus'] as const) number(d[k],`${label} ${k}`); if (bounds(d).min < 0) throw Error(`${label} lower bound cannot be negative.`); }
export function validateDataset(input: unknown): Dataset {
  const d = input as Dataset; if (!d || d.schemaVersion !== 7) throw Error('Expected a CellAtlas schemaVersion 7 dataset.');
  const ids = new Set<string>(), revisions = new Set<string>();
  for (const key of collections) { if (!Array.isArray(d[key]) || d[key].length > 10000) throw Error(`Invalid ${key} collection.`); for (const r of d[key]) { for (const k of ['id','lineageId','name','createdAt','source','notes'] as const) text(r[k],k); if (!r.id || !r.lineageId || !r.name.trim() || ids.has(r.id)) throw Error('Revision IDs and names must be present; IDs must be unique.'); if (!Number.isInteger(r.revision) || r.revision < 1 || !Number.isFinite(Date.parse(r.createdAt))) throw Error('Invalid revision number or date.'); const revisionKey = `${key}/${r.lineageId}/${r.revision}`; if (revisions.has(revisionKey)) throw Error('Duplicate revision in a lineage.'); revisions.add(revisionKey); ids.add(r.id); } }
  const materials = new Map(d.materials.map(r=>[r.id,r])), electrodes = new Map(d.electrodes.map(r=>[r.id,r])), parts = new Map(d.parts.map(r=>[r.id,r])), boms = new Map(d.boms.map(r=>[r.id,r]));
  for (const m of d.materials) { if (!['Cathode','Anode'].includes(m.electrodeType)) throw Error('Invalid electrode type.'); number(m.cs,'Cs',true); for(const k of ['supplier','chemistry'] as const) text(m[k],k); }
  for (const e of d.electrodes) { if (!materials.has(e.materialId)) throw Error('Electrode material revision is missing.'); number(e.utility,'Utility',true); if (e.utility!=null&&e.utility>100) throw Error('Utility cannot exceed 100%.'); number(e.density,'Density',true); number(e.collectorThicknessUm,'Collector thickness',true); if (!['Al','Cu','Other','Unknown'].includes(e.collectorMaterial)) throw Error('Invalid collector material.'); text(e.collectorGrade,'Collector grade'); validateDimension(e.loading,'Loading',true);validateDimension(e.thickness,'Electrode thickness',true); if (e.thickness && e.collectorThicknessUm!=null && e.collectorThicknessUm/1000>e.thickness.nominal) throw Error('Collector foil cannot exceed measured total electrode thickness.'); }
  for (const p of d.parts) { if (!['Housing','Separator','Insulation','Lid','Terminal','Collector','Other'].includes(p.role)) throw Error('Invalid component role.'); for(const k of ['partNumber','material','supplier','drawing'] as const) text(p[k],k); validateDimension(p.thickness,'Component thickness'); validateDimension(p.internalSpace,'Housing internal space',true); number(p.width,'Width',true); number(p.height,'Height',true); if (p.role==='Housing'&&(!p.internalSpace||p.internalSpace.nominal<=0)) throw Error('Housing requires positive internal stack space.'); }
  for (const b of d.boms) { if(parts.get(b.housingId)?.role!=='Housing') throw Error('BOM requires a pinned housing revision.'); if(!Array.isArray(b.items)||b.items.length>1000)throw Error('Invalid BOM items.');for(const item of b.items){if(!parts.has(item.partId))throw Error('BOM component revision missing.');if(!Number.isInteger(item.quantity)||item.quantity<1)throw Error('BOM quantities must be positive integers.');if(!['perCell','perStack','perSeparatorLayer','inventoryOnly'].includes(item.usage))throw Error('Invalid BOM usage.');if(parts.get(item.partId)?.role==='Housing'&&item.usage!=='inventoryOnly')throw Error('Housing wall thickness is not a stack contribution.');} }
  for(const p of d.plans){const c=electrodes.get(p.cathodeId),a=electrodes.get(p.anodeId);if(!c||!a||materials.get(c.materialId)?.electrodeType!=='Cathode'||materials.get(a.materialId)?.electrodeType!=='Anode'||!boms.has(p.bomId))throw Error('Plan requires pinned cathode, anode and BOM revisions.');if(!['specified','automatic'].includes(p.mode))throw Error('Invalid sheet-count mode.');for(const k of ['sheets','stacks','extraSeparatorLayers'] as const)if(!Number.isInteger(p[k])||p[k]<(k==='extraSeparatorLayers'?0:1))throw Error(`${k} must be a valid integer.`);validateDimension(p.stackClearance,'Stack clearance');validateDimension(p.assemblyClearance,'Assembly clearance');number(p.overlapAreaCm2,'Overlap area',true);number(p.minimumNp,'N/P minimum');number(p.maximumNp,'N/P maximum',true);if(p.minimumNp<=0||p.maximumNp!=null&&p.maximumNp<p.minimumNp)throw Error('Invalid N/P limits.');}
  return structuredClone(d);
}
function canonical(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';const v=value as Record<string,unknown>;return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}
export function assertAppendOnly(before: Dataset, after: Dataset) { for(const key of collections){const map=new Map(after[key].map(r=>[r.id,r as Version]));for(const old of before[key]){const next=map.get(old.id);if(!next||canonical(next)!==canonical(old))throw Error(`Immutable ${key} revision changed or removed. Create a new revision instead.`);}} }
export function mergeDatasets(a: Dataset,b: Dataset): Dataset{const result=structuredClone(a);for(const key of collections){const map=new Map<string, unknown>(a[key].map(r=>[r.id,r]));for(const row of b[key]){if(map.has(row.id)&&canonical(map.get(row.id))!==canonical(row))throw Error(`Import conflict on immutable revision ${row.id}.`);map.set(row.id,row);} (result as unknown as Record<string,unknown>)[key]=[...map.values()];}return validateDataset(result);}
