import { useState } from 'react';
import { bounds, dimension as d } from '../domain/types';
import type { Collection, Dataset, Entity, Material, Electrode, Part, Bom } from '../domain/types';
import { Field, RevisionSelect, DimensionInput, optionalNumber } from './Fields';
import { capacity } from '../domain/engine';
export function Editor({kind,initial,data,onCancel,onSave}:{kind:Collection;initial:Entity;data:Dataset;onCancel:()=>void;onSave:(value:Entity)=>Promise<void>}){const [value,setValue]=useState<Entity>(structuredClone(initial)),[error,setError]=useState(''),[saving,setSaving]=useState(false);function patch(p:Record<string,unknown>){setValue(v=>({...v,...p} as Entity))}const text=(key:string,label:string,optional=false)=><Field label={label} value={(value as unknown as Record<string,string>)[key]} optional={optional} onChange={v=>patch({[key]:v})}/>;const numeric=(key:string,label:string)=><Field type="number" label={label} value={(value as unknown as Record<string,number|null>)[key]} optional onChange={v=>patch({[key]:optionalNumber(v)})}/>;const select=(key:string,label:string,options:string[])=><label>{label}<select value={(value as unknown as Record<string,string>)[key]} onChange={e=>patch({[key]:e.target.value})}>{options.map(x=><option key={x}>{x}</option>)}</select></label>;
let fields;
if(kind==='materials'){fields=<><div className="fields">{select('electrodeType','Electrode family',['Cathode','Anode'])}{text('chemistry','Chemistry')}{text('supplier','Supplier',true)}{numeric('cs','Specific capacity Cs · mAh/g')}</div><p className="hint">Cs belongs to the material revision. Electrode utility and coating loading are stored separately.</p></>}
if(kind==='electrodes'){const e=value as Electrode,m=data.materials.find(x=>x.id===e.materialId);let calculated='Capacity data incomplete.';try{if(m){const c=capacity(e,m);calculated=`C per face: ${c.nominal.toFixed(4)} mAh/cm² · min ${c.min.toFixed(4)} · max ${c.max.toFixed(4)} · both-face total ${c.bothFaces.toFixed(4)}`}}catch{}fields=<><RevisionSelect label="Pinned material revision" value={e.materialId} rows={data.materials} onChange={materialId=>patch({materialId})}/><div className="fields">{numeric('utility','Utility · %')}{numeric('density','Calendered coating density · g/cm³ (recorded)')}{select('collectorMaterial','Collector foil material',['Unknown','Al','Cu','Other'])}{numeric('collectorThicknessUm','Collector foil thickness · µm')}{text('collectorGrade','Collector grade / specification',true)}</div><DimensionInput label="Total dry coating loading, both faces" unit="g/m²" value={e.loading} optional onChange={loading=>patch({loading})}/><DimensionInput label="Measured electrode total thickness, including foil" value={e.thickness} optional onChange={thickness=>patch({thickness})}/><div className="calculated">{calculated}</div><p className="hint">Density is recorded; it does not overwrite measured thickness. Loading excludes the foil. Equal loading per face is assumed. Lower and upper deviations are absolute values in the shown units.</p></>}
if(kind==='parts'){const p=value as Part;fields=<><div className="fields">{select('role','Component role',['Housing','Separator','Insulation','Lid','Terminal','Collector','Other'])}{text('partNumber','Part number',true)}{text('material','Material',true)}{text('supplier','Supplier',true)}{text('drawing','Drawing / CAD reference',true)}{numeric('width','Width · mm (optional)')}{numeric('height','Height · mm (optional)')}</div><DimensionInput label={p.role==='Housing'?'Housing wall thickness (metadata)':'Component thickness'} value={p.thickness} onChange={thickness=>patch({thickness:thickness??d(0)})}/>{p.role==='Housing'&&<DimensionInput label="Available internal stack space" value={p.internalSpace} optional onChange={internalSpace=>patch({internalSpace})}/>}<p className="hint">A drawing is stored as a reference; binary CAD files are not attached in this prototype. Housing wall thickness is metadata; the calculation uses internal space directly.</p></>}
if(kind==='boms'){const b=value as Bom;fields=<><RevisionSelect label="Pinned housing revision" value={b.housingId} rows={data.parts.filter(p=>p.role==='Housing')} onChange={housingId=>patch({housingId})}/><h3>Component instances</h3>{b.items.map((item,i)=><div className="bomItem" key={i}><RevisionSelect label="Pinned component revision" value={item.partId} rows={data.parts.filter(p=>p.role!=='Housing')} onChange={partId=>patch({items:b.items.map((v,j)=>j===i?{...v,partId}:v)})}/><Field label="Quantity multiplier" type="number" value={item.quantity} onChange={v=>patch({items:b.items.map((x,j)=>j===i?{...x,quantity:Number(v)}:x)})}/><label>Usage<select value={item.usage} onChange={ev=>patch({items:b.items.map((v,j)=>j===i?{...v,usage:ev.target.value}:v)})}><option value="perCell">Per cell</option><option value="perStack">Per stack</option><option value="perSeparatorLayer">Per separator layer</option><option value="inventoryOnly">Inventory only · no stack thickness</option></select></label><button type="button" onClick={()=>patch({items:b.items.filter((_,j)=>j!==i)})}>Remove</button></div>)}<button type="button" onClick={()=>patch({items:[...b.items,{partId:data.parts.find(p=>p.role!=='Housing')?.id??'',quantity:1,usage:'perCell'}]})}>+ Add component</button><p className="hint">Separator thickness is multiplied by (2n + extra layers) × stack count. Other components contribute only according to their explicit usage. Lid, terminal and collector parts can be inventory-only.</p></>}
return <div className="modalBackdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Revision editor"><div className="sectionHead"><h2>{initial.id&&data[kind].some(v=>v.id===initial.id)?'Create next revision':'Create record'}</h2><button onClick={onCancel} disabled={saving}>Close</button></div><form onSubmit={async ev=>{ev.preventDefault();setError('');setSaving(true);try{await onSave(value)}catch(e){setError((e as Error).message);setSaving(false)}}}><div className="fields">{text('name','Record name')}{text('source','Source / test reference',true)}</div>{fields}{text('notes','Notes',true)}{error&&<p role="alert" className="error">{error}</p>}<div className="modalFooter"><span className="hint">Existing revisions remain unchanged.</span><button className="primary" disabled={saving}>{saving?'Saving…':'Save new revision'}</button></div></form></section></div>}
