import { collections } from '../domain/types.ts';
import type { Dataset, StoredDataset } from '../domain/types.ts';
import { assertAppendOnly, validateDataset } from '../domain/validation.ts';
import type { Repository } from './repository.ts';
export class IndexedDbRepository implements Repository {
  private db: Promise<IDBDatabase>;
  constructor(name='cellatlas-engineering-v7',factory:IDBFactory=indexedDB){this.db=new Promise((resolve,reject)=>{const req=factory.open(name,1);req.onupgradeneeded=()=>{for(const key of collections)req.result.createObjectStore(key,{keyPath:'id'});req.result.createObjectStore('metadata');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async load():Promise<StoredDataset|null>{const db=await this.db;return new Promise((resolve,reject)=>{const tx=db.transaction([...collections,'metadata'],'readonly'),data={schemaVersion:7} as Dataset;let version:number|undefined;for(const key of collections){const r=tx.objectStore(key).getAll();r.onsuccess=()=>{(data as unknown as Record<string,unknown>)[key]=r.result;};}const meta=tx.objectStore('metadata').get('version');meta.onsuccess=()=>{version=meta.result;};tx.oncomplete=()=>{try{resolve(version===undefined?null:{version,data:validateDataset(data)});}catch(e){reject(e);}};tx.onerror=()=>reject(tx.error);});}
  async save(value:Dataset,expectedVersion:number):Promise<number>{const data=validateDataset(value),db=await this.db;return new Promise((resolve,reject)=>{const tx=db.transaction([...collections,'metadata'],'readwrite');let failure:Error|undefined;const previous={schemaVersion:7} as Dataset;let ready=0;const apply=()=>{if(++ready!==collections.length+1)return;try{if(version!==expectedVersion)throw Error('Data changed in another tab. Reload before saving.');if(version>0)assertAppendOnly(previous,data);for(const key of collections)for(const row of data[key])tx.objectStore(key).put(row);tx.objectStore('metadata').put(version+1,'version');}catch(e){failure=e as Error;tx.abort();}};let version=0;for(const key of collections){const r=tx.objectStore(key).getAll();r.onsuccess=()=>{(previous as unknown as Record<string,unknown>)[key]=r.result;apply();};}const r=tx.objectStore('metadata').get('version');r.onsuccess=()=>{version=r.result??0;apply();};tx.oncomplete=()=>resolve(version+1);tx.onabort=()=>reject(failure??tx.error??Error('Save aborted.'));tx.onerror=()=>reject(failure??tx.error);});}
}
